apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildkit-cache
  namespace: bytesail-system
  labels:
    app.kubernetes.io/managed-by: bytesail
    bytesail.io/component: builder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
